### ISSUE TITLE
Only the first log is saved

### ISSUE THREAD

**Issue by miguelcorreia19** [ofkindness/winston-postgres-transport#27]
Hi,

I have a problem:

Every time that I start my application and I call `logger.log({...})`, the message is registered in the DB. 
But after that, when I call it again, never enter in the log function:

https://github.com/ofkindness/winston-postgres-transport/blob/61b995772005cc3a7d9a28ad2c01bd7e75f5e68c/lib/winston-postgres-transport.js#L125

I can query, so the connection is perfect, but just the first log is saved.

I think the problem is here:

https://github.com/ofkindness/winston-postgres-transport/blob/61b995772005cc3a7d9a28ad2c01bd7e75f5e68c/lib/winston-postgres-transport.js#L144-L155

I leave here my suggestion to solve this:

```
    const logQuery = callbackify(
      () => sql`INSERT INTO ${sql(tableName)} ${sql(log, ...tableFields)}`
    );

    logQuery((error, data) => {
      if (error) {
        return handleCallback(callback, error);
      }
      return handleCallback(callback, null, data);
    });
```

**Comment by VinodVitana** [comment]
I am also facing this issue. @miguelcorreia19 's fix worked for me. @ofkindness , if you are maintaining this, can you fix this.

-Vinod.

**Comment by ofkindness** [comment]
Thank you for info, I'll provide fix ASAP

**Comment by miguelcorreia19** [comment]
Thanks!

Btw, you can explain how I can call the function [init](https://github.com/ofkindness/winston-postgres-transport/blob/9b66e0c7e1df69eddf03711ac06fb14d74e9a244/lib/winston-postgres-transport.js#L88-L97) by the logger?
To create the tables when start...

**Comment by ofkindness** [comment]
It was never meant to be used somewhere outside the test, but still you can use it directly from transport itself:
```js
const transport = new PostgresTransport({
  postgresUrl,
});
await transport.init();
```
